namespace: argocd

resources:
- https://github.com/argoproj-labs/argocd-agent/install/kubernetes/agent?ref=release-0.7
- agent-redis-networkpolicy.yaml
- application-controller-cluster-admin-role.yaml

images:
- name: ghcr.io/argoproj-labs/argocd-agent/argocd-agent
  newName: quay.io/argoprojlabs/argocd-agent
  newTag: v0.7.0

patches:
  - patch: |
      - op: replace
        path: /data/agent.mode
        value: autonomous
      - op: replace
        path: /data/agent.server.address
        value: argocd-agent-principal-argocd.apps.$SUBDOMAIN
      - op: replace
        path: /data/agent.namespace
        value: argocd
      - op: replace
        path: /data/agent.creds
        value: "mtls:CN=([^,]+)"
      - op: replace
        path: /data/agent.redis.address
        value: argocd-redis:6379
    target:
      kind: ConfigMap
      name: argocd-agent-params
