apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: crl-cer-1
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceNamespaces:
  - managed-cluster
  - crl-cer-1
  - crl-cer-2
  sourceRepos:
  - '*'
